/**
 * Initial file content for each project template. Used when a project is
 * first created so the user lands on a runnable scaffold instead of an
 * empty directory.
 *
 * Keep these tiny on purpose: enough to start the dev server and hit
 * the preview URL, no more.
 */

export interface ScaffoldFile {
  path: string;
  content: string;
}

const VITE_REACT_PACKAGE_JSON = JSON.stringify(
  {
    name: "app",
    private: true,
    version: "0.0.1",
    type: "module",
    scripts: {
      dev: "vite --host 0.0.0.0",
      build: "vite build",
      preview: "vite preview --host 0.0.0.0"
    },
    dependencies: {
      react: "^18.3.1",
      "react-dom": "^18.3.1"
    },
    devDependencies: {
      "@vitejs/plugin-react": "^4.3.1",
      vite: "^5.4.0"
    }
  },
  null,
  2
);

const VITE_REACT_VITE_CONFIG = `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  server: { host: "0.0.0.0", port: 5173 }
});
`;

const VITE_REACT_INDEX_HTML = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Singulary app</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
`;

const VITE_REACT_MAIN = `import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App.jsx";

createRoot(document.getElementById("root")).render(<App />);
`;

const VITE_REACT_APP = `export default function App() {
  return (
    <main style={{ fontFamily: "system-ui", padding: "2rem" }}>
      <h1>Hello from Singulary</h1>
      <p>Edit <code>src/App.jsx</code> and save to hot-reload.</p>
    </main>
  );
}
`;

const EXPRESS_PACKAGE_JSON = JSON.stringify(
  {
    name: "app",
    private: true,
    version: "0.0.1",
    type: "module",
    scripts: {
      dev: "node --watch index.js",
      start: "node index.js"
    },
    dependencies: {
      express: "^4.21.0"
    }
  },
  null,
  2
);

const EXPRESS_INDEX = `import express from "express";

const app = express();
const port = Number(process.env.PORT) || 3000;

app.get("/", (_req, res) => {
  res.json({ ok: true, message: "Hello from Singulary" });
});

app.listen(port, "0.0.0.0", () => {
  console.log(\`API listening on http://0.0.0.0:\${port}\`);
});
`;

const WORKER_PACKAGE_JSON = JSON.stringify(
  {
    name: "worker",
    private: true,
    version: "0.0.1",
    type: "module",
    scripts: { dev: "node --watch worker.js", start: "node worker.js" }
  },
  null,
  2
);

const WORKER_INDEX = `let tick = 0;
setInterval(() => {
  tick += 1;
  console.log(JSON.stringify({ level: "info", msg: "worker tick", tick }));
}, 5000);

console.log("Worker started. Edit worker.js to define real work.");
`;

const PYTHON_FASTAPI_MAIN = `from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def root():
    return {"ok": True, "message": "Hello from Singulary"}
`;

const PYTHON_REQUIREMENTS = `fastapi==0.115.0
uvicorn[standard]==0.30.6
`;

const STATIC_INDEX_HTML = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Singulary static site</title>
    <style>
      body { font-family: system-ui; padding: 2rem; }
    </style>
  </head>
  <body>
    <h1>Hello from Singulary</h1>
    <p>Drop your static files in this folder and they'll be served by nginx.</p>
  </body>
</html>
`;

const GO_MAIN = `package main

import (
  "fmt"
  "log"
  "net/http"
  "os"
)

func main() {
  port := os.Getenv("PORT")
  if port == "" {
    port = "8080"
  }
  http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintln(w, "Hello from Singulary")
  })
  log.Printf("listening on :%s", port)
  if err := http.ListenAndServe("0.0.0.0:"+port, nil); err != nil {
    log.Fatal(err)
  }
}
`;

const GO_MOD = `module app

go 1.22
`;

const SHARED_README = (name: string, runtime: string) =>
  `# ${name}

Generated by Singulary.

Runtime: \`${runtime}\`

Open the chat panel and ask the agent to extend this scaffold.
`;

const SHARED_GITIGNORE = `node_modules/
dist/
build/
out/
.next/
.turbo/
.cache/
target/
__pycache__/
*.pyc
.venv/
.env
.env.local
*.log
`;

export type ScaffoldBuilder = (projectName: string) => ScaffoldFile[];

const SCAFFOLDS: Record<string, ScaffoldBuilder> = {
  "node-22": (name) => [
    { path: "README.md", content: SHARED_README(name, "node") },
    { path: ".gitignore", content: SHARED_GITIGNORE },
    { path: "package.json", content: VITE_REACT_PACKAGE_JSON },
    { path: "vite.config.js", content: VITE_REACT_VITE_CONFIG },
    { path: "index.html", content: VITE_REACT_INDEX_HTML },
    { path: "src/main.jsx", content: VITE_REACT_MAIN },
    { path: "src/App.jsx", content: VITE_REACT_APP }
  ],
  "node-20": (name) => [
    { path: "README.md", content: SHARED_README(name, "node") },
    { path: ".gitignore", content: SHARED_GITIGNORE },
    { path: "package.json", content: EXPRESS_PACKAGE_JSON },
    { path: "index.js", content: EXPRESS_INDEX }
  ],
  "bun-1": (name) => [
    { path: "README.md", content: SHARED_README(name, "bun") },
    { path: ".gitignore", content: SHARED_GITIGNORE },
    { path: "package.json", content: VITE_REACT_PACKAGE_JSON },
    { path: "vite.config.js", content: VITE_REACT_VITE_CONFIG },
    { path: "index.html", content: VITE_REACT_INDEX_HTML },
    { path: "src/main.jsx", content: VITE_REACT_MAIN },
    { path: "src/App.jsx", content: VITE_REACT_APP }
  ],
  "python-3.12": (name) => [
    { path: "README.md", content: SHARED_README(name, "python") },
    { path: ".gitignore", content: SHARED_GITIGNORE },
    { path: "main.py", content: PYTHON_FASTAPI_MAIN },
    { path: "requirements.txt", content: PYTHON_REQUIREMENTS }
  ],
  "go-1.22": (name) => [
    { path: "README.md", content: SHARED_README(name, "go") },
    { path: ".gitignore", content: SHARED_GITIGNORE },
    { path: "go.mod", content: GO_MOD },
    { path: "main.go", content: GO_MAIN }
  ],
  "static-nginx": (name) => [
    { path: "README.md", content: SHARED_README(name, "static") },
    { path: ".gitignore", content: SHARED_GITIGNORE },
    { path: "index.html", content: STATIC_INDEX_HTML }
  ],
  worker: (name) => [
    { path: "README.md", content: SHARED_README(name, "worker") },
    { path: ".gitignore", content: SHARED_GITIGNORE },
    { path: "package.json", content: WORKER_PACKAGE_JSON },
    { path: "worker.js", content: WORKER_INDEX }
  ]
};

/**
 * Return the file scaffold for a project template. Unknown templates get a
 * README + .gitignore only.
 */
export function getScaffoldFor(templateId: string | null, runtimeKind: string, projectName: string): ScaffoldFile[] {
  if (templateId && SCAFFOLDS[templateId]) {
    return SCAFFOLDS[templateId](projectName);
  }
  // Fallback by runtime kind so plain `runtimeKind: "node"` still gets the
  // basic Vite/React scaffold.
  if (runtimeKind === "node" || runtimeKind === "bun") {
    return SCAFFOLDS["node-22"](projectName);
  }
  if (runtimeKind === "python") return SCAFFOLDS["python-3.12"](projectName);
  if (runtimeKind === "go") return SCAFFOLDS["go-1.22"](projectName);
  if (runtimeKind === "static") return SCAFFOLDS["static-nginx"](projectName);
  return [
    { path: "README.md", content: SHARED_README(projectName, runtimeKind) },
    { path: ".gitignore", content: SHARED_GITIGNORE }
  ];
}
